name: stream_disposer
description: "StreamDisposer"
version: 0.0.4
repository: https://github.com/ssk-flutter/stream_disposer
issue_tracker: https://github.com/ssk-flutter/stream_disposer/issues
homepage: https://github.com/ssk-flutter/stream_disposer
documentation: https://github.com/ssk-flutter/stream_disposer
topics: [stream, dispose, cancel]
funding: [https://github.com/ssk-flutter/stream_disposer]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta:

dev_dependencies:
  test: ^1.16.0
